version: '3'
services:
#    mariadb:
#        build:
#            context: mariadb/
#            dockerfile: Dockerfile
#        image: mariadb
    wordpress:
        build:
            context: wordpress/
            dockerfile: Dockerfile
        image: wordpress
#        depends_on:
#           - mariadb
#    nginx:
#        build:
#            context: nginx/
#            dockerfile: Dockerfile
#        image: nginx
#        ports:
#            - 443:443
#        depends_on:
#           - wordpress
